# Generated by Django 3.1.5 on 2021-07-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
